version: '3.8'

services:

  buletina:
    image: "sirikon/srkbz-buletina-custom:${VARIATION_NAME}_${VARIATION_VERSION}"
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        BULETINA_VERSION: ${BULETINA_VERSION}
        VARIATION_NAME: ${VARIATION_NAME}
    command: "sh -c 'cd workdir && java -jar --enable-preview ../buletina.fat.jar'"
    volumes:
      - ../variations/${VARIATION_NAME}:/app/workdir:ro
    environment:
      BULETINA_PORT: "8080"
      BULETINA_BASE_URL: "http://127.0.0.1:8080"
      BULETINA_JWT_SECRET: "secret"
      BULETINA_DATABASE_URL: "jdbc:postgresql://db:5432/buletina?user=buletina&password=buletina"
      BULETINA_SMTP_SERVER: "smtp"
      BULETINA_SMTP_USERNAME: "username"
      BULETINA_SMTP_PASSWORD: "password"
      BULETINA_SMTP_SENDER: "buletina@example.com"
      BULETINA_DEBUG_TEMPLATES: "true"
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - smtp
      - db

  smtp:
    image: gessnerfl/fake-smtp-server:1.6.1
    restart: always
    environment: 
      "server.port": 8081
      "fakesmtp.port": 25
    ports:
      - 127.0.0.1:8081:8081

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: buletina
      POSTGRES_USER: buletina
      POSTGRES_PASSWORD: buletina
