version: '3.8'

services:

  buletina:
    image: "sirikon/srkbz-buletina-custom:${VARIATION_NAME}_${VARIATION_VERSION}"
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        BULETINA_VERSION: ${BULETINA_VERSION}
        VARIATION_NAME: ${VARIATION_NAME}
